# wisp: AI ghost-text command suggestions for zsh. Generated by `wisp init zsh`.
#
# zsh-autosuggestions must be loaded first: it draws the grey suggestion text and provides
# the accept keys (right arrow, End, Ctrl-F). wisp replaces its suggestion with the model's.

[[ -o interactive ]] || return 0
if (( ! $+functions[_zsh_autosuggest_highlight_apply] )); then
  print -u2 "wisp: load zsh-autosuggestions before wisp"
  return 1
fi
zmodload zsh/net/socket zsh/zselect zsh/datetime || return 1
autoload -Uz add-zle-hook-widget add-zsh-hook

typeset -g _WISP_BIN=__WISP_BIN__
typeset -g _WISP_SOCKET=__WISP_SOCKET__
typeset -g _WISP_LOG=${_WISP_SOCKET:r}.log
typeset -g _WISP_FD= _WISP_CMD= _WISP_SENT_BUFFER=
typeset -gi _WISP_SEQ=0 _WISP_RETRY_AT=0

# _wisp_show sets POSTDISPLAY itself, so autosuggestions must not wrap it.
ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(_wisp_show)

# Sets REPLY to $1 encoded as a JSON string.
_wisp_json() {
  emulate -L zsh
  local s=${1//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\t'/\\t}
  s=${s//[[:cntrl:]]/}
  REPLY="\"$s\""
}

# Connects to the daemon, starting it if needed. After a failed start, waits a minute
# before trying again so a broken install does not stall every prompt.
_wisp_connect() {
  emulate -L zsh
  [[ -n $_WISP_FD ]] && return 0
  (( EPOCHSECONDS >= _WISP_RETRY_AT )) || return 1
  if ! zsocket $_WISP_SOCKET 2>/dev/null; then
    mkdir -p -m 700 ${_WISP_SOCKET:h}
    ( cd / && exec $_WISP_BIN daemon --socket $_WISP_SOCKET </dev/null >>$_WISP_LOG 2>&1 & )
    local attempt connected=0
    for attempt in {1..20}; do
      zselect -t 5
      if zsocket $_WISP_SOCKET 2>/dev/null; then
        connected=1
        break
      fi
    done
    if (( ! connected )); then
      _WISP_RETRY_AT=$(( EPOCHSECONDS + 60 ))
      print -u2 "wisp: daemon did not start, see $_WISP_LOG"
      return 1
    fi
  fi
  _WISP_FD=$REPLY
  zle -F $_WISP_FD _wisp_recv
}

_wisp_disconnect() {
  emulate -L zsh
  [[ -n $_WISP_FD ]] || return 0
  zle -F $_WISP_FD 2>/dev/null
  exec {_WISP_FD}>&-
  _WISP_FD=
}

_wisp_send() {
  emulate -L zsh
  # A daemon that just died must not kill the shell with SIGPIPE.
  trap '' PIPE
  _wisp_connect || return 1
  print -r -u $_WISP_FD -- $1 2>/dev/null || _wisp_disconnect
}

# Called by zle when the daemon replies with "<seq>\t<suggestion>".
_wisp_recv() {
  emulate -L zsh
  local line
  if ! IFS= read -r -u $1 line; then
    _wisp_disconnect
    return 0
  fi
  (( ${line%%$'\t'*} == _WISP_SEQ )) || return 0
  zle _wisp_show -- "${line#*$'\t'}"
  # Handlers run between keystrokes, so zle does not repaint on its own.
  zle -R
}

_wisp_show() {
  emulate -L zsh
  local suggestion=$1
  [[ $suggestion == "$BUFFER"* ]] && (( CURSOR == $#BUFFER )) || return 0
  _zsh_autosuggest_highlight_reset
  POSTDISPLAY=${suggestion#"$BUFFER"}
  _zsh_autosuggest_highlight_apply
}
zle -N _wisp_show

_wisp_line_changed() {
  emulate -L zsh
  [[ $BUFFER == "$_WISP_SENT_BUFFER" ]] && return 0
  _WISP_SENT_BUFFER=$BUFFER
  (( ++_WISP_SEQ ))
  (( $#BUFFER && CURSOR == $#BUFFER )) || return 0
  _wisp_json $BUFFER
  _wisp_send "{\"t\":\"req\",\"seq\":$_WISP_SEQ,\"buf\":$REPLY}"
}
add-zle-hook-widget line-pre-redraw _wisp_line_changed

_wisp_preexec() {
  _WISP_CMD=$1
}
add-zsh-hook preexec _wisp_preexec

_wisp_precmd() {
  local exit_status=$?
  emulate -L zsh
  local cmd cwd pane histfile
  _wisp_json $_WISP_CMD; cmd=$REPLY
  _wisp_json $PWD; cwd=$REPLY
  _wisp_json ${WEZTERM_PANE:-}; pane=$REPLY
  _wisp_json ${HISTFILE:-}; histfile=$REPLY
  _WISP_CMD= _WISP_SENT_BUFFER=
  (( ++_WISP_SEQ ))
  _wisp_send "{\"t\":\"done\",\"seq\":$_WISP_SEQ,\"cmd\":$cmd,\"status\":$exit_status,\"cwd\":$cwd,\"pane\":$pane,\"histfile\":$histfile}"
}
# First, so $? is still the status of the command that just finished.
precmd_functions=(_wisp_precmd $precmd_functions)
